import { Button, ThemeProvider, createTheme } from "@mui/material";
import TextField from "@mui/material/TextField";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { FaFileUpload } from "react-icons/fa";
import { MdSend } from "react-icons/md";

import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Navbar2 from "@/components/NavBar";
import ParticleBackground from "../components/particleBackground";

export default function Upload() {
  //theme for mui
  const theme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: "#e6e6e6",
        contrastText: "#fff",
      },
    },
  });

  const [title, settitle] = useState("");
  const [Content, setContent] = useState("");
  const [dop, setDop] = useState("");
  const [video, setVideo] = useState(null);
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    setpdfFile(file);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const docRef = await addDoc(collection(database, "documents"), {
        title,
        Content,
        dop,
        video,
      });

      console.log("Document written with ID: ", docRef.id);
    } catch (error) {
      console.error("Error adding document: ", error);
    }
  };
  return (
    <>
      <Head>
        <title>Chaari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Navbar2 />
      <main>
        <ParticleBackground />
        <div className="h-auto  flex flex-col justify-center items-center py-8 ">
          <div
            style={{ zIndex: "1" }}
            className="  px-12 py-10 w-11/12 sm:w-10/12 md:w-4/5 lg:w-4/5 xl:w-1/2 glass-morphic border-2 border-black rounded-md flex flex-col box-border"
          >
            <div className="text-5xl text-white text-center">Upload Videos</div>

            <div className="flex flex-col  ">
              <ThemeProvider theme={theme}>
                <div className="flex flex-col mt-10 mb-10">
                  <div className="flex flex-col  mb-10">
                    <TextField
                      id="outlined-basic"
                      value={title}
                      sx={{ maxwidth: 500 }}
                      onChange={(e) => {
                        settitle(e.target.value);
                      }}
                      label="Enter title here"
                      variant="outlined"
                    />
                  </div>
                </div>

                <div className="flex flex-row gap-6 flex-wrap justify-center">
                  {/* <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <DatePicker
                      label="Select Date"
                      sx={{ minWidth: 320 }}
                      onChange={(event, selectedValue) => {
                        setDop(selectedValue);
                      }}
                      renderInput={(params) => (
                        <TextField {...params} label="Select a Date" />
                      )}
                    />
                  </LocalizationProvider> */}

                  <div className="flex flex-col  mb-10">
                    <label
                      htmlFor="filePicker"
                      className="block font-medium mb-2"
                    >
                      <Button
                        component="span"
                        variant="outlined"
                        sx={{
                          p: "12px",
                          minWidth: 320,
                          textTransform: "capitalize",
                          color: "rgba(255, 255, 255, 0.7)",
                          fontWeight: "400",
                          fontSize: "1rem",
                        }}
                      >
                        Select Video
                        <FaFileUpload
                          fontSize="1.45em"
                          style={{
                            marginLeft: "auto",
                            color: "rgba(255, 255, 255, 1)",
                          }}
                        />
                      </Button>
                    </label>
                    <input
                      type="file"
                      id="filePicker"
                      style={{ display: "none" }}
                      accept=".pdf"
                      className="py-2 px-4 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                </div>

                <Button
                  variant="outlined"
                  sx={{
                    fontSize: "1.2rem",
                    padding: "10px 0",
                    maxwidth: 240,
                  }}
                  endIcon={<MdSend />}
                >
                  Submit
                </Button>
              </ThemeProvider>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
