import { Button, ThemeProvider, createTheme } from "@mui/material";
import { IoClose } from "react-icons/io5";

import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Navbar2 from "@/components/NavBar";
import ParticleBackground from "../components/particleBackground";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Modal from "react-modal";
import { FaPlay, FaTimes } from "react-icons/fa";
import ReactPlayer from "react-player";
import Pagination from "@material-ui/lab/Pagination";
const videosPerPage = 5;

export default function VideoView() {
  //theme for mui
  const theme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: "#e6e6e6",
        contrastText: "#fff",
      },
    },
  });
  const textWhiteStyle = {
    color: "white",
  };

  const modalBodyStyle = {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  };
  const [currentPage, setCurrentPage] = useState(1);
  const [videos, setVideos] = useState([]);
  const [selectedVideo, setSelectedVideo] = useState(null);
  const indexOfLastVideo = currentPage * videosPerPage;
  const indexOfFirstVideo = indexOfLastVideo - videosPerPage;
  const currentVideos = videos.slice(indexOfFirstVideo, indexOfLastVideo);

  const totalPages = Math.ceil(videos.length / videosPerPage);

  const handleChangePage = (event, page) => {
    setCurrentPage(page);
  };
  const handleDeleteVideo = (index) => {
    const updatedVideos = [...videos];
    updatedVideos.splice(index, 1);
    setVideos(updatedVideos);
  };
  const handleOpenModal = (video) => {
    setSelectedVideo(video);
  };

  const handleCloseModal = () => {
    setSelectedVideo(null);
  };

  const generateSampleData = () => {
    const sampleData = [
      {
        slNo: 1,
        trainingLevel: "PHYSICAL Wellbeing Beginner",
        selectedCourse: "Warm ups – Prāramba Vyāyamā",
        video: "https://example.com/video1",
      },
      {
        slNo: 2,
        trainingLevel: "PHYSICAL Wellbeing Intermediate",
        selectedCourse: "Stretches",
        video: "https://example.com/video2",
      },
    ];
    setVideos(sampleData);
  };

  useEffect(() => {
    generateSampleData();
  }, []);
  return (
    <>
      <Head>
        <title>Chaari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Navbar2 />
      <main>
        <ParticleBackground />
        <div className="h-auto flex flex-col justify-center items-center py-8">
          <div
            style={{ zIndex: "1" }}
            className="px-12 py-10 w-11/12 sm:w-10/12 md:w-4/5 lg:w-4/5 xl:w-1/2 glass-morphic border-2 border-black rounded-md flex flex-col box-border"
          >
            <div className="text-5xl text-white text-center">View Videos</div>

            <div className="flex flex-col">
              <ThemeProvider theme={createTheme()}>
                <TableContainer>
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell style={textWhiteStyle}>Sl.no</TableCell>
                        <TableCell style={textWhiteStyle}>
                          Training Level
                        </TableCell>
                        <TableCell style={textWhiteStyle}>
                          Selected Course
                        </TableCell>
                        <TableCell style={textWhiteStyle}>Video</TableCell>
                        <TableCell style={textWhiteStyle}>Delete/Row</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {currentVideos.map((video, index) => (
                        <TableRow key={index}>
                          <TableCell style={textWhiteStyle}>
                            {video.slNo}
                          </TableCell>
                          <TableCell style={textWhiteStyle}>
                            {video.trainingLevel}
                          </TableCell>
                          <TableCell style={textWhiteStyle}>
                            {video.selectedCourse}
                          </TableCell>
                          <TableCell style={textWhiteStyle}>
                            <FaPlay
                              className="video-icon"
                              onClick={() => handleOpenModal(video.video)}
                            />
                          </TableCell>
                          <TableCell style={textWhiteStyle}>
                            <Button
                              variant="contained"
                              onClick={() => handleDeleteVideo(index)}
                            >
                              Delete
                            </Button>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </TableContainer>
                <Pagination
                  count={totalPages}
                  page={currentPage}
                  onChange={handleChangePage}
                  color="primary"
                  className="mt-3"
                />
              </ThemeProvider>
            </div>
            <Modal
              style={modalBodyStyle}
              isOpen={selectedVideo !== null}
              onRequestClose={handleCloseModal}
              contentLabel="Video Modal"
              className="video-modal"
              overlayClassName="video-modal-overlay"
            >
              <div className="modal-header">
                <FaTimes
                  className="cancel-icon"
                  style={{ fontSize: "24px", alignSelf: "flex-end" }}
                  onClick={handleCloseModal}
                />
              </div>
              <div className="modal-body flex justify-center items-center">
                <ReactPlayer url={selectedVideo} controls />
              </div>
            </Modal>
          </div>
        </div>
      </main>
    </>
  );
}
